In [338]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import feature_extraction
from heapq import nlargest
from functools import reduce
from operator import add
from scipy.spatial import distance
from numpy import array
import sklearn.metrics as metrics
from scipy.linalg import svd
import copy
import scipy.spatial.distance as distance
import Levenshtein as lev
import heapq
import random
import numpy
import time
import string
import json
import re

In [261]:
global recipes_before_removing_element
global flattened_recipes_set
global unique_ingredients
global unique_ingredients_after_removing_hidden

f = open('train.json')
data = json.load(f)

recipe_list = []

for i in data:
    #split with comma to get the cuisine.
    split1=str(i).split(',')
    #clean the strings with split and regex
    split2 = split1[1].split(':')
    cuisine = re.sub(r'[.\W]','',split2[1])
    #get the recipe id
    recipe_split = split1[0].split(': ')
    recipe_id=recipe_split[1]
    #keep only the pepperoni guys
    if cuisine=='italian':
        #splitting with [ because ingredients have the only list in the string
        split3=str(i).split('[')
        #final cut
        ingredients=split3[1].split(',')
        #removing ' from the strings
        ingredients = [s.translate(str.maketrans('','',string.punctuation)) for s in ingredients]
        if len(ingredients)>2:
            recipe_list.append(ingredients)
            
            
#remove whitespaces
for i,obj in enumerate(recipe_list):
    recipe_list[i] = [x.strip() for x in recipe_list[i]]

print(len(recipe_list))            
#make the 2d list 1d so we can count occurences easily
flattened_recipes_set = copy.deepcopy(recipe_list)
flattened_recipes_set = reduce(lambda x,y :x+y ,flattened_recipes_set)


#find the unique ingredients list of all the italian dataset
unique_ingredients = list(numpy.unique(numpy.array(flattened_recipes_set)))
print(len(unique_ingredients))            

#randomize the recipes
random.shuffle(recipe_list)


#get the first 1000 randomized items
set_of_recipes = recipe_list[:1000]


recipes_before_removing_element = copy.deepcopy(set_of_recipes)

hidden_items_to_remove = []

#remove 1 random ingredient from every recipes
for i,obj in enumerate(set_of_recipes):
    #randomise the list and remove the first element
    random.shuffle(set_of_recipes[i])
    hidden_items_to_remove.append(set_of_recipes[i][0])
    set_of_recipes[i].pop(0)


recipes=copy.deepcopy(set_of_recipes)
print(len(hidden_items_to_remove))
#unique ingredients have all the items except the hidden FOR ALL ITALIAN RECIPES
unique_ingredients_without_hidden = list(set(unique_ingredients) - set(hidden_items_to_remove))



7801
2932
1000


In [295]:
vectorized_matrix_m =[]
for i,obj in enumerate(recipe_list):
    vector = [0] * len(unique_ingredients_without_hidden)
    current_recipe = recipe_list[i]
    for j,obj in enumerate(current_recipe):
        if current_recipe[j] in unique_ingredients_without_hidden:
            vector[unique_ingredients_without_hidden.index(current_recipe[j])] = 1
    vectorized_matrix_m.append(vector)
print(len(vectorized_matrix_m))
print(len(vectorized_matrix_m[0]))

7801
2543


In [294]:
vectorized_matrix_r =[]
for i,obj in enumerate(recipes):
    vector = [0] * len(unique_ingredients_without_hidden)
    current_recipe = recipes[i]
    for j,obj in enumerate(current_recipe):
        if current_recipe[j] in unique_ingredients_without_hidden:
            vector[unique_ingredients_without_hidden.index(current_recipe[j])] = 1
    vectorized_matrix_r.append(vector)
print(len(vectorized_matrix_r))
print(len(vectorized_matrix_r[0]))

1000
2543


In [269]:
# Popular_without_recipes_ingredients is a dict but without the ingredients 
# of the current recipe of the loop.

score_list = []
#popular is a dictionary with : (ingredient,times igredient used in all the recipes)
popular = dict((x,flattened_recipes_set.count(x)) for x in set(flattened_recipes_set))
for i in recipes:
    popular_without_recipes_ingredients = list(filter(lambda x: x in i, popular))
    max_value = max(popular_without_recipes_ingredients)
    score_list.append(max_value)
most_popular_score_list = score_list

In [321]:

vectorized_matrix_r = numpy.array(vectorized_matrix_r)
vectorized_matrix_m = numpy.array(vectorized_matrix_m)

D = metrics.pairwise.pairwise_distances(vectorized_matrix_r, vectorized_matrix_m, metric='jaccard')

print(D)


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/metrics/pairwise.py:1735: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)


[[0. 1. 1. ... 1. 1. 1.]
 [1. 0. 1. ... 1. 1. 1.]
 [1. 1. 0. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [350]:
#getting the length similar indexes for the recipes

lists_with_scores_for_every_n = []
for length in range(1,100):
    
    most_similar = []
    scores_ucf = []
    most_similar_values = []
    
    for i,obj in enumerate(recipes):



        #the Jaccard similarity of an item with itself is always 1.
        #we are going to get the n+1 largest values so we can pop out
        #the one with itself.

        #gives the indexes of the n+1 largest values of jaccard
        most_similar = heapq.nsmallest(length+1, range(len(a)), D[i].take)
        most_similar.pop(0)

        #gives the values of jaccard of the n+1 largest values
        jaccard_values = heapq.nsmallest(length+1, D[i])
        jaccard_values.pop(0)      
        scores_1=[]

        ingredients_without_current = list(set(unique_ingredients_without_hidden) - set(recipes[i]))

        for j,obj in enumerate(unique_ingredients_without_hidden):
            if unique_ingredients_without_hidden[j] in recipes[i]:
                scores_1.append(0)
            else:
                index_of_ingredient = unique_ingredients_without_hidden.index(unique_ingredients_without_hidden[j])

                jaccard_dot_matrix_sum = 0
                jaccard_sum = 0

                for k in range(length):
                    m = most_similar[k]
                    jaccard_dot_matrix_sum += jaccard_values[k] * vectorized_matrix_m[m][index_of_ingredient]
                    jaccard_sum += jaccard_values[k]

                if jaccard_sum != 0:    
                    scores_1.append(jaccard_dot_matrix_sum/jaccard_sum)
                else:
                    scores_1.append(0) 
        scores_ucf.append(scores_1)
    lists_with_scores_for_every_n.append(scores_ucf)

In [388]:
lists_of_precisions = []
for length in range(0,99):
    found_sum = 0
    for j,obj in enumerate(recipes):
        hidden_element = list(set(recipes_before_removing_element[j]) - set(recipes[j]))
        current_lengths_scores = lists_with_scores_for_every_n[length]

        #for K=1 we just want the maximum value
        max_value = max(current_lengths_scores[j])
        #print(max_value)
        max_index = current_lengths_scores[j].index(max_value)

        ingredient_proposed_by_the_algorithm = unique_ingredients_without_hidden[max_index]

        Ratio = lev.ratio(hidden_element[0].lower(),ingredient_proposed_by_the_algorithm.lower())
        if Ratio>0.5:
#             print("hidden element:",hidden_element[0])
#             print("found:",ingredient_proposed_by_the_algorithm)
#             print("++++++++")
            found_sum += 1
#     print("found sum:",found_sum)
#     print(found_sum/len(recipes))
#     print("------------")
    lists_of_precisions.append(found_sum/len(recipes))
print(lists_of_precisions)
print("best is at:",lists_of_precisions.index(max(lists_of_precisions)))

[0.01, 0.015, 0.017, 0.018, 0.025, 0.023, 0.028, 0.023, 0.025, 0.028, 0.022, 0.021, 0.022, 0.023, 0.02, 0.022, 0.023, 0.025, 0.024, 0.023, 0.027, 0.028, 0.026, 0.031, 0.031, 0.029, 0.026, 0.026, 0.028, 0.025, 0.026, 0.026, 0.023, 0.023, 0.023, 0.025, 0.025, 0.022, 0.02, 0.022, 0.02, 0.019, 0.017, 0.02, 0.021, 0.021, 0.02, 0.021, 0.02, 0.021, 0.021, 0.018, 0.015, 0.015, 0.017, 0.018, 0.017, 0.015, 0.013, 0.015, 0.014, 0.016, 0.016, 0.016, 0.015, 0.016, 0.015, 0.015, 0.017, 0.016, 0.015, 0.015, 0.014, 0.012, 0.014, 0.015, 0.016, 0.019, 0.019, 0.019, 0.017, 0.017, 0.018, 0.018, 0.019, 0.019, 0.019, 0.021, 0.019, 0.02, 0.021, 0.021, 0.019, 0.018, 0.019, 0.019, 0.02, 0.019, 0.019]
best is at: 23


In [417]:
#jaccard of each ingredient with the other
Distance_ingredients = []

for i in unique_ingredients_without_hidden:
    distance_ingredient_current = []
    for j in unique_ingredients_without_hidden:
        s1 = set(i)
        s2 = set(j)
        if len(s1.union(s2))==0:
            distance_ingredient_current.append(0)
        else:
            distance_ingredient_current.append(len(s1.intersection(s2)) / len(s1.union(s2)))
    Distance_ingredients.append(distance_ingredient_current)

print(Distance_ingredients[2])

[0.0, 0.2, 1.0, 0.45454545454545453, 0.3076923076923077, 0.2, 0.2, 0.1, 0.3076923076923077, 0.1875, 0.25, 0.4375, 0.2, 0.26666666666666666, 0.2, 0.26666666666666666, 0.2, 0.15384615384615385, 0.3125, 0.4, 0.26666666666666666, 0.23076923076923078, 0.15384615384615385, 0.3684210526315789, 0.2857142857142857, 0.2727272727272727, 0.0, 0.13333333333333333, 0.5, 0.3076923076923077, 0.2857142857142857, 0.4166666666666667, 0.5454545454545454, 0.2, 0.3333333333333333, 0.2857142857142857, 0.42105263157894735, 0.07142857142857142, 0.42857142857142855, 0.18181818181818182, 0.3333333333333333, 0.18181818181818182, 0.3, 0.29411764705882354, 0.2857142857142857, 0.2857142857142857, 0.23529411764705882, 0.46153846153846156, 0.23076923076923078, 0.25, 0.09090909090909091, 0.375, 0.3333333333333333, 0.26666666666666666, 0.07692307692307693, 0.46153846153846156, 0.38461538461538464, 0.35714285714285715, 0.4, 0.45454545454545453, 0.2727272727272727, 0.25, 0.15384615384615385, 0.2777777777777778, 0.17647058

In [437]:
print(len(Distance_ingredients))
print(len(Distance_ingredients[0]))
print(unique_ingredients_without_hidden[5])
print(unique_ingredients_without_hidden[2])

2543
2543
toast
black cod


In [440]:
length = 4

most_similar = []
scores_icf = []
most_similar_values = []

for i,obj in enumerate(recipes):
    Distance_ingredients = numpy.array(Distance_ingredients)
    #gives the indexes of the n+1 largest values of jaccard
    most_similar = heapq.nlargest(length+1, range(len(Distance_ingredients[i])), Distance_ingredients[i].take)
    most_similar.pop(0)

    #gives the values of jaccard of the n+1 largest values
    jaccard_values = heapq.nlargest(length+1, Distance_ingredients[i])
    jaccard_values.pop(0)      
    scores_1=[]

    ingredients_without_current = list(set(unique_ingredients_without_hidden) - set(recipes[i]))
    
    for j,obj in enumerate(unique_ingredients_without_hidden): 
        if unique_ingredients_without_hidden[j] in recipes[i]:
            scores_1.append(0)
        else:
            index_of_recipe = recipe_list.index(recipes[i])
            jaccard_dot_matrix_sum = 0
            jaccard_sum = 0

            for k in range(length):
                m = most_similar[k]
                
                #in vectorized_m i dont need to find the index
                #because the first 1000 recipes corresponds to the first 1000 recipes of the
                #recipe_list that the matrix was built. it was randomized before so it doesnt matter
                #that these are the first 1000
                
                jaccard_dot_matrix_sum += jaccard_values[k] * vectorized_matrix_m[index_of_recipe][m]
                jaccard_sum += jaccard_values[k]

            if jaccard_sum != 0:    
                scores_1.append(jaccard_dot_matrix_sum/jaccard_sum)
            else:
                scores_1.append(0) 
        scores_icf.append(scores_1)

In [441]:
print(scores_icf[1])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [423]:
found_sum = 0
for j,obj in enumerate(recipes):
    hidden_element = list(set(recipes_before_removing_element[j]) - set(recipes[j]))
    #current_lengths_scores = lists_with_scores_for_every_n[length]

    #for K=1 we just want the maximum value
    max_value = max(scores_icf[j])
    #print(max_value)
    max_index = scores_icf[j].index(max_value)

    ingredient_proposed_by_the_algorithm = unique_ingredients_without_hidden[max_index]

    Ratio = lev.ratio(hidden_element[0].lower(),ingredient_proposed_by_the_algorithm.lower())
    if Ratio>0.2:
        print("hidden element:",hidden_element[0])
        print("found:",ingredient_proposed_by_the_algorithm)
        print("++++++++")
        found_sum += 1

print("found sum:",found_sum)
lists_of_precisions.append(found_sum/len(recipes))



found sum: 0
